version: '3.5'
services:
# single node deployment
  cockroach1:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    hostname: roach1
    volumes:
      - 'roach1:/cockroach/cockroach-data'
    ports:
      - "26257:26257"
      - "8080:8080"
    command: "start-single-node --insecure && ./cockroach sql --execute=\"CREATE DATABASE indexer;\" --insecure"
  algod:
    image: algorand/algod:stable
    container_name: algod-testnet
    environment:
      ADMIN_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      PROFILE: "conduit"
      NETWORK: "testnet"
    ports:
      - "4190:8080"
  conduit:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - algod
      - cockroach1
    volumes:
      - './run_data:/data'
    network_mode: "host"
    restart: on-failure:3
volumes:
  roach1:
    external: false
  roach2:
    external: false
  roach3:
    external: false
networks:
  cockroach-net:
    driver: bridge


# multi node deployment
# # Node 1
#  cockroach1:
#    image: cockroachdb/cockroach:latest
#    container_name: cockroach1
#    hostname: cockroach1
#    networks:
#      - cockroach-net
#    ports:
#      - 26257:26257   # Cockroach Database port
#      - 8080:8080     # Cockroach UI Panel port
#    volumes:
#      - roach1:/cockroach/cockroach-data
#    command: start --insecure --join=cockroach1,cockroach2,cockroach3
#
#  # Node 2
#  cockroach2:
#    image: cockroachdb/cockroach:latest
#    container_name: cockroach2
#    hostname: cockroach2
#    networks:
#      - cockroach-net
#    volumes:
#      - roach2:/cockroach/cockroach-data
#    command: start --insecure --join=cockroach1,cockroach2,cockroach3
#
#  # Node 3
#  cockroach3:
#    image: cockroachdb/cockroach:latest
#    container_name: cockroach3
#    hostname: cockroach3
#    networks:
#      - cockroach-net
#    volumes:
#      - roach3:/cockroach/cockroach-data
#    command: start --insecure --join=cockroach1,cockroach2,cockroach3
#
#  # First Time Initialization of Cockroach DB
#  init-roach1:
#    image: cockroachdb/cockroach:latest
#    container_name: init-cockroach
#    depends_on:
#      - cockroach1
#    restart: "no"
#    networks:
#      - cockroach-net
#    entrypoint: [ "bash", "-c" ,"./cockroach init --insecure --host cockroach1:26257 && ./cockroach sql --execute=\"CREATE DATABASE indexer;\" --insecure | wc || exit" ]
